@startuml
skinparam handwritten false
skinparam shadowing<<with_shadow>> true

interface IDomainService
interface IDomainStep
IDomainStep : execute()
interface IDecideStepsExt
interface IDomainRevokableStep
IDomainRevokableStep : rollback()
interface IIdentityResolver
interface IDomainExtension
interface IPlugable
IPlugable <|-- IDomainExtension: extend
IPlugable <|-- IIdentityResolver: extend
interface IModelAttachmentExt
IModelAttachmentExt : explain()
IModelAttachmentExt : render()
abstract StepsExecTemplate
abstract BaseDomainAbility
BaseDomainAbility : getExtension()
BaseDomainAbility : firstExtension()
BaseDomainAbility : defaultExtension()
StepsExecTemplate : execute()
DDD : {static} getContainer()
DDD : {static} findAbility()
DDD : {static} findSteps()
IDecideStepsExt : decideSteps()
IIdentityResolver : match(IDomainModel)

IDomainService <|-- IDomainStep
IDomainStep <|-- IDomainRevokableStep
IDomainService <|-- BaseDomainAbility

IDomainExtension <|-- IDecideStepsExt: extend
IDomainExtension <|-- IModelAttachmentExt: extend

IIdentityResolver <|-- Pattern
IIdentityResolver <|-- Partner

BaseDomainAbility <-- DDD: find
IDomainStep <-- DDD: find

IDomainExtension <-- BaseDomainAbility: locate

IDomainExtension --> Pattern: bind
IDomainExtension --> Partner: bind

DDD --> Container : get
Container : {static} PluginLoader

Container --> IPlugable : load

Partner : code
Pattern : code
IDomainExtension : code

StepsExecTemplate --> IDomainStep: orchestration
@enduml
